#!/usr/bin/perl
use strict;
use Nsd;

if ($#ARGV < 0) {
	print ("Usage: $0 <domain>\n");
	exit();
}
foreach my $arg (0 .. $#ARGV) {
	debugDomain(lc($ARGV[$arg]));
}

sub debugDomain {
	my ($domain) = @_;
	my $nsd = new DP::Nsd();
	$nsd->setDebug(0);
	my $err_code = $nsd->checkDomains($domain);

	## possible outcomes:
	# 	1, domain is fine
	#	0, missing from config file
	#	-1, zone file does not exist
	#	-2, zone file and config file missing

	if ($err_code != 1) { 
		if ($err_code == 0) {
			print "[!]:  $domain is not in the NSD configuration file\n";
		}
		elsif ($err_code == -1) {
			print "[!]:  $domain has a missing zone file\n";
		}
		elsif ($err_code == -2) {
			print "[=]:  $domain exists and is fine.\n";
			return 0;
		}

		print "[*]: Fixing problems for $domain...\n";
		$nsd->removeDomain($domain);
		$nsd->addDomain($domain);
		return 0;
	}
	print "[!]: $domain needs to be added, please do so.\n";
	return 1;
}
