#!/usr/bin/perl
use strict;

use strict;
use Nsd;

if ($#ARGV < 0) {
	print ("Usage: $0 <domain1> <domain2> ...\n");
	exit();
}

main();

sub main {
	my $domains_removed = $#ARGV+1;
	my $total_domains = $#ARGV+1;
	my $nsd = new DP::Nsd();

	# loop through each domain and remove as necessary
	my $domain;
	foreach my $arg (0 .. $#ARGV) {
		$domain = lc($ARGV[$arg]);
		
		if (!$nsd->removeDomain($domain)) {
			--$domains_removed;
		}

	}

	print("[=]:  $domains_removed/$total_domains domains removed.\n");
	return 1;
}

